name: CI Pipeline with GitHub Secrets

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Step to set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step to install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      # Step to build and start containers
      - name: Build and start containers
        run: docker-compose -f docker-compose.yml up -d --build

       # Step to run npm install inside the container
      - name: Install dependencies in auth-service
        run: docker exec auth-service npm install 

      - name: Wait for services to be ready
        run: sleep 20

      # Step to run tests
      - name: Run tests in Docker
        run: docker exec auth-service npm run jest 

      # Step to shut down containers
      - name: Shut down Docker containers
        run: docker-compose down
