name: CI Pipeline with GitHub Secrets

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      NODE_ENV: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Build
        run: docker-compose -f docker-compose.yml up -d --build

      - name: Wait for services to be ready
        run: sleep 20

      - name: Run tests in Docker
        run: docker-compose exec auth-service npm test

      - name: Shut down Docker containers
        run: docker-compose down
